
server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB









#  控制台接入
#java -Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -jar target/sentinel-dashboard.jar